# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         DNS-EasyDNS
version:      0.04
version_from: lib/DNS/EasyDNS.pm
installdirs:  site
requires:
    HTTP::Request::Common:         1.19
    LWP::UserAgent:                2.001

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
